# Generated by Django 5.2.6 on 2025-10-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField()),
                ('autor', models.CharField()),
                ('año', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('PK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categoria')),
            ],
        ),
    ]
