# Generated by Django 5.2.6 on 2025-10-10 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='PK',
            new_name='categoria',
        ),
    ]
