# Generated by Django 5.2.6 on 2025-10-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Libros', '0002_rename_pk_libro_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='libros', to='Categorias.categoria'),
        ),
    ]
