# Generated by Django 5.2.6 on 2025-10-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0003_alter_libro_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'ordering': ['-id'], 'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
