# Generated by Django 5.2.6 on 2025-10-12 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Libros', '0004_alter_libro_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libro',
            options={'verbose_name': 'Libro', 'verbose_name_plural': 'Libros'},
        ),
    ]
